### ISSUE TITLE
Videos do not display

### ISSUE THREAD

**Issue by Stack3r** [antonic901/xbox-youtube#8]
Hello, after the recent updates I am now having issues where either videos will only show a black screen with audio or the app will lock up completely. I am running videos at 360p and this was not an issue before

**Comment by antonic901** [comment]
Which video did you try to play? I couldn't replicate that problem on my Xbox

**Comment by Stack3r** [comment]
It's really happening with multiple videos, I've also cleared the cache and that didn't help, try g gundam master Asia death 360p.

**Comment by Stack3r** [comment]
https://youtu.be/97sMo_cS5Yg

**Comment by Stack3r** [comment]
I think I may have resolved the issue by changing XBMC advanced settings cache to 0, which will save files to the hard drive while being used. Although I did not have this issue or need with the older version

**Comment by antonic901** [comment]
I can't reproduce problem on my Xbox. I'm not using advancesetting.xml at all. I don't know what could be problem for you... Sometimes invidious API is slow or not responsive. Maybe that was your problem?

**Comment by antonic901** [comment]
Couldn't reproduce error on my machine. Din't get enough info
